name: Scheduled Scraping

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:      # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Create credentials directory
        run: mkdir -p credentials
        
      - name: Set up credentials
        run: echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' > credentials/cantonese-katakana-0f740ce346b9.json
        
      - name: Run scraper
        run: node scrapeData.mjs
