// Example of how to construct the credentials object from individual environment variables
function getGoogleCredentials() {
  // Check if all required environment variables are present
  const requiredEnvVars = [
    'GOOGLE_CLIENT_EMAIL',
    'GOOGLE_PRIVATE_KEY',
    'GOOGLE_PROJECT_ID'
  ];
  
  const missingVars = requiredEnvVars.filter(varName => !process.env[varName]);
  if (missingVars.length > 0) {
    throw new Error(`Missing required environment variables: ${missingVars.join(', ')}`);
  }

  // Construct the credentials object
  const credentials = {
    type: 'service_account',
    project_id: process.env.GOOGLE_PROJECT_ID,
    private_key: process.env.GOOGLE_PRIVATE_KEY.replace(/\\n/g, '\n'), // Fix escaped newlines
    client_email: process.env.GOOGLE_CLIENT_EMAIL,
  };

  console.log('Credentials object constructed successfully');
  return credentials;
}

// Example usage
try {
  const credentials = getGoogleCredentials();
  console.log('Project ID:', credentials.project_id);
  console.log('Client Email:', credentials.client_email);
  console.log('Private key length:', credentials.private_key.length);
} catch (error) {
  console.error('Error setting up credentials:', error.message);
}
